name: Comment on failing build

on:
  check_run:
    types: [completed]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Check if the build is failing
    steps:
      - name: Check if the build is failing
        run: |
          ! curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.antiope-preview+json" "https://api.github.com/repos/CodelyTV/pr-size-labeler/commits/${{ github.ref }}/check-runs" | grep -q failure

      - name: Comment if the build failed
        if: failure()
        uses: peter-evans/commit-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            The build has **failed**, take care! We recoment you to
            - Squash all the commits when it gets green again
            - Do a merge
